/**
 * Compound word dictionary for common Chinese multi-character words.
 * Maps compound words to their English meanings.
 * Used by the test question generator to provide word-level meanings.
 */
export const COMPOUND_WORD_MAP: Record<string, string> = {
  // Common greetings & expressions
  "你好": "hello",
  "大家": "everyone",
  "谢谢": "thank you",
  "再见": "goodbye",
  "没有": "don't have",
  "不是": "is not",
  "可以": "can; may",
  "因为": "because",
  "所以": "therefore",
  "但是": "but; however",
  "如果": "if",
  "虽然": "although",
  "已经": "already",
  "非常": "very; extremely",
  "一起": "together",
  "什么": "what",
  "怎么": "how; why",
  "为什么": "why",
  "这里": "here",
  "那里": "there",
  "哪里": "where",

  // People & family
  "妈妈": "mother; mom",
  "爸爸": "father; dad",
  "爷爷": "grandfather",
  "奶奶": "grandmother",
  "姐姐": "older sister",
  "哥哥": "older brother",
  "弟弟": "younger brother",
  "妹妹": "younger sister",
  "朋友": "friend",
  "同学": "classmate",
  "老师": "teacher",
  "学生": "student",
  "孩子": "child; children",
  "大人": "adult",
  "小孩": "child; kid",
  "伙伴": "companion; partner",

  // School & learning
  "学校": "school",
  "学习": "study; learn",
  "上学": "go to school",
  "放学": "finish school",
  "教室": "classroom",
  "作业": "homework",
  "考试": "exam; test",
  "知识": "knowledge",
  "练习": "practice",
  "读书": "read; study",
  "写字": "write characters",
  "上课": "attend class",
  "下课": "finish class",

  // Nature & weather
  "天气": "weather",
  "下雨": "rain",
  "下雪": "snow",
  "太阳": "sun",
  "月亮": "moon",
  "星星": "star",
  "春天": "spring",
  "夏天": "summer",
  "秋天": "autumn",
  "冬天": "winter",
  "花草": "flowers and grass",
  "大树": "big tree",
  "小鸟": "little bird",
  "小鱼": "little fish",
  "小河": "stream; creek",
  "大海": "ocean; sea",
  "高山": "tall mountain",
  "白云": "white cloud",
  "蓝天": "blue sky",

  // Places
  "家里": "at home",
  "外面": "outside",
  "里面": "inside",
  "上面": "above; on top",
  "下面": "below; underneath",
  "前面": "in front",
  "后面": "behind",
  "旁边": "beside; next to",
  "公园": "park",
  "商店": "shop; store",
  "医院": "hospital",
  "图书馆": "library",

  // Actions & activities
  "开心": "happy; joyful",
  "高兴": "happy; glad",
  "快乐": "happy; joyful",
  "生气": "angry",
  "害怕": "afraid; scared",
  "喜欢": "like; enjoy",
  "知道": "know",
  "觉得": "feel; think",
  "希望": "hope; wish",
  "帮助": "help",
  "告诉": "tell",
  "回家": "go home",
  "出去": "go out",
  "进来": "come in",
  "起来": "get up; stand up",
  "出来": "come out",
  "回来": "come back",
  "过来": "come over",
  "看见": "see; catch sight of",
  "听见": "hear",
  "发现": "discover; find",
  "开始": "begin; start",
  "结束": "end; finish",
  "准备": "prepare; ready",
  "决定": "decide",
  "认为": "think; believe",
  "认识": "know; recognize",
  "记住": "remember",
  "忘记": "forget",

  // Body & health
  "眼睛": "eyes",
  "耳朵": "ears",
  "嘴巴": "mouth",
  "头发": "hair",
  "身体": "body",
  "生病": "get sick",
  "休息": "rest",

  // Food & daily life
  "吃饭": "eat (a meal)",
  "喝水": "drink water",
  "睡觉": "sleep",
  "起床": "get up (from bed)",
  "洗手": "wash hands",
  "穿衣": "get dressed",
  "东西": "thing; stuff",
  "水果": "fruit",
  "苹果": "apple",
  "西瓜": "watermelon",

  // Time
  "今天": "today",
  "明天": "tomorrow",
  "昨天": "yesterday",
  "现在": "now",
  "以前": "before; previously",
  "以后": "after; later",
  "早上": "morning",
  "中午": "noon",
  "下午": "afternoon",
  "晚上": "evening; night",
  "时候": "time; moment",
  "时间": "time",

  // Numbers & measure
  "一个": "one (thing)",
  "多少": "how many; how much",
  "一些": "some; a few",
  "许多": "many; a lot",

  // Animals
  "小猫": "kitten; little cat",
  "小狗": "puppy; little dog",
  "蝴蝶": "butterfly",
  "蜘蛛": "spider",
  "蚂蚁": "ant",
  "孔雀": "peacock",

  // Colors & descriptions
  "漂亮": "beautiful; pretty",
  "好看": "good-looking",
  "可爱": "cute; lovely",
  "聪明": "clever; smart",
  "勇敢": "brave",
  "认真": "serious; careful",
  "仔细": "careful; attentive",
  "简单": "simple; easy",
  "容易": "easy",
  "困难": "difficult",
  "重要": "important",
  "特别": "special; especially",

  // Directions & movement
  "左边": "left side",
  "右边": "right side",
  "东方": "east",
  "西方": "west",
  "南方": "south",
  "北方": "north",

  // Misc common words
  "事情": "matter; thing",
  "问题": "question; problem",
  "办法": "method; way",
  "故事": "story",
  "消息": "news; message",
  "声音": "sound; voice",
  "颜色": "color",
  "地方": "place",
  "世界": "world",
  "国家": "country; nation",
  "城市": "city",
  "农村": "countryside",
  "自己": "oneself",
  "别人": "other people",
  "一定": "certainly; must",
  "可能": "maybe; possible",
  "应该": "should; ought to",
  "需要": "need",
  "愿意": "willing",
  "只好": "have to; can only",
  "终于": "finally; at last",
  "马上": "immediately; at once",
  "赶快": "hurry up",
  "慢慢": "slowly",
  "轻轻": "gently; lightly",
  "安静": "quiet; peaceful",
  "热闹": "lively; bustling",
};

/**
 * Look up the English meaning of a compound word.
 * Returns the meaning if found, empty string if not.
 */
export function lookupCompoundMeaning(compoundWord: string): string {
  return COMPOUND_WORD_MAP[compoundWord] ?? "";
}
